name: upload to drive
on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    if: contains( github.event.pull_request.labels.*.name, 'test') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Upload files
        env:
          TOKEN: ${{secrets.GOOGLE_API_TOKEN}}
        run: |
          cd ./.scripts/
          echo $TOKEN >> ./token.json
          npm install
          GOOGLE_APPLICATION_CREDENTIALS=./token.json npm run upload
          rm -f ./token.json
